# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: team-managment

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: BanspTech
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: BanspTech
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm install
      - run: pm2 restart app.js
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
